name: hmsc-hpc
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pyreadr
  - scipy
  - ujson
  - rpy2
  - ipython-sql
  - pip
  - pip: 
      - tensorflow[and-cuda]2.19
      - tensorflow-probability[tf]
      - git+https://github.com/hmsc-r/hmsc-hpc.git
      